name: Bump Release Version

on:
  workflow_dispatch:
    inputs:
      part:
        type: choice
        required: true
        options:
          - "-"
          - "major (X._._)"
          - "minor (_.X._)"
          - "bugfix (_._.X)"
      dry_run:
        type: boolean
        default: false

jobs:
  bump-release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: test "bugfix (_._.X)" = "${{ inputs.part }}"

      - run: cat deploy/mchart/Chart.yaml

      - run: |
          CHART_APP_VERSION=$(yq .appVersion deploy/mchart/Chart.yaml)
          echo "CHART_APP_VERSION=${CHART_APP_VERSION}" >> "$GITHUB_ENV"
          echo "CHART_APP_VERSION=${CHART_APP_VERSION}"

          CHART_VERSION=$(yq .version deploy/mchart/Chart.yaml)
          echo "CHART_VERSION=${CHART_VERSION}" >> "$GITHUB_ENV"
          echo "CHART_VERSION=${CHART_VERSION}"

      - run: |
          test "${CHART_APP_VERSION}" = "${CHART_VERSION}"

      - run: |
          NEW_CHART_APP_VERSION="2.11.1"
          NEW_CHART_VERSION="2.11.1"

      - run: |
          yq -i .appVersion = '${NEW_CHART_APP_VERSION}'" deploy/mchart/Chart.yaml
          yq -i ".version = '${NEW_CHART_APP_VERSION}'" deploy/mchart/Chart.yaml

      - run: cat deploy/mchart/Chart.yaml

      - run: |
          yq .appVersion deploy/mchart/Chart.yaml
          yq .version deploy/mchart/Chart.yaml

      - run: git commit -m "Bump version to ${NEW_CHART_APP_VERSION}"

      - run: git tag

      - run: git tag "-begin-${NEW_CHART_VERSION}"

      - run: git push origin "-begin-${NEW_CHART_VERSION}"

      - run: git push origin main
